DELETE FROM MOVIE_ACTOR;
DELETE FROM ACTOR;
DELETE FROM RATING;
DELETE FROM MOVIE;
DELETE FROM DIRECTOR;

ALTER SEQUENCE SEQ_ID_RATING RESTART WITH 1;
ALTER SEQUENCE SEQ_DIRECTOR_ID RESTART WITH 1;
ALTER SEQUENCE SEQ_ACTOR_ID RESTART WITH 1;
ALTER SEQUENCE SEQ_ID_MOVIE RESTART WITH 1;
