CREATE SEQUENCE SEQ_ID_RATING START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE RATING (
    RATING_ID NUMBER(38) NOT NULL,
    SOURCE VARCHAR2(50) NOT NULL,
    RATING VARCHAR2(50) NOT NULL,
    MOVIE_ID NUMBER(38) NOT NULL,
    CONSTRAINT PK_RATING PRIMARY KEY (RATING_ID),
    CONSTRAINT FK_RATING_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID)
);
