CREATE SEQUENCE SEQ_ID_RATING START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE RATING (
    OID_RATING NUMBER(38) NOT NULL,
    SOURCE VARCHAR2(50) NOT NULL,
    RATING VARCHAR2(50) NOT NULL,
    OID_MOVIE NUMBER(38) NOT NULL,
    CONSTRAINT PK_RATING PRIMARY KEY (OID_RATING),
    CONSTRAINT FK_RATING_OID_MOVIE FOREIGN KEY (OID_MOVIE) REFERENCES MOVIE(OID_MOVIE)
);
